set_property MARK_DEBUG true [get_nets {dbg_cnt[0]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[1]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[2]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[3]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[4]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[5]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[6]}]
set_property MARK_DEBUG true [get_nets {dbg_cnt[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/clk_wiz_0/locked]

set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[12]}]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]

set_property MARK_DEBUG true [get_nets design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/CLK]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dbg_cnt[0]} {dbg_cnt[1]} {dbg_cnt[2]} {dbg_cnt[3]} {dbg_cnt[4]} {dbg_cnt[5]} {dbg_cnt[6]} {dbg_cnt[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[0]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[1]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[2]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[3]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[4]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[5]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[6]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[7]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[8]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[9]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[10]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[11]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[12]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[13]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[14]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/D[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/CLK]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/clk_wiz_0/locked]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
