create_clock -period 6.250 -name <adc_clk> [get_ports hdmi_clk_p]

set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FIFO_DUALCLOCK_MACRO_inst/genblk5_0.fifo_18_bl_1.fifo_18_bl_1/WREN]
set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FIFO_DUALCLOCK_MACRO_inst/genblk5_0.fifo_18_bl_1.fifo_18_bl_1/RST]
set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/data_cs_reg*/CLR]

set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/state_cs_reg/CLR]


set_property MARK_DEBUG false [get_nets design_1_i/TTC0_WAVE1_OUT_0]

set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[12]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[11]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[22]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[24]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[26]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[15]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[31]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[9]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[12]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[17]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[19]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[23]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[29]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[30]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[8]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[10]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[16]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[20]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[25]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[27]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[7]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[13]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[14]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[18]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[21]}]
set_property MARK_DEBUG false [get_nets {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/fifo_di[28]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/adc16dv160_input_0/inst/adc_clk]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[0]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[1]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[2]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[3]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[4]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[5]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[6]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[7]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[8]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[9]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[10]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[11]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[12]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[13]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[14]} {design_1_i/adc16dv160_input_0/inst/data_receiver_inst/D[15]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_adc_clk]
