create_clock -period 6.250 -name <adc_clk> [get_ports hdmi_clk_p]

set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FIFO_DUALCLOCK_MACRO_inst/genblk5_0.fifo_18_bl_1.fifo_18_bl_1/WREN]
set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FIFO_DUALCLOCK_MACRO_inst/genblk5_0.fifo_18_bl_1.fifo_18_bl_1/RST]
set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/data_cs_reg*/CLR]
set_false_path -from [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/FSM_sequential_state_cs_reg*/C] -to [get_pins design_1_i/adc16dv160_input_0/inst/data_receiver_inst/data_extend_inst/state_cs_reg/CLR]

set_property MARK_DEBUG true [get_nets {je_OBUF[0]}]
set_property MARK_DEBUG true [get_nets ADC_CLK_OUT]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {je_OBUF[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list ADC_CLK_OUT]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
